version: 2.1

commands:
  restore-cache-dependency:
    steps:
      - restore_cache:
          keys:
            - v1-golang-playground-{{ checksum "go.sum" }}
  lint:
    parameters:
      GOLANGCI_LINT_VERSION:
        type: string
        default: 1.21.0
    steps:
      - run:
          name: lint
          command: |
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v<< parameters.GOLANGCI_LINT_VERSION >>
            make lint
  test:
    steps:
      - run:
          name: test
          command: |
            go mod vendor
            make ci.test
            bash <(curl -s https://codecov.io/bash) -f ./codecov.yml
  save-cache-dependency:
    steps:
      - save_cache:
          paths:
            - "/go/pkg/mod"
          key: v1-golang-playground-{{ checksum "go.sum" }}

jobs:
  test:
    docker:
      - image: golang:1.13
    environment:
      GO111MODULE: "on"
      GOSUMDB: "off"
    steps:
      - checkout
      # - restore-cache-dependency
      - lint
      - test
      # - save-cache-dependency

workflows:
    test:
      jobs:
        - test
